#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 16 14:13:44 2021

@author: AlvinDevasia
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Uber pickups in NYC')